### ISSUE TITLE
[Error] Mulitple errors when trying to load example addon

### ISSUE THREAD

**Issue by Lauorez** [MeteorDevelopment/meteor-addon-template#1]
The first error is, that the branch "master-SNAPSHOT" does not work. When you change is to "master" it goes on but hangs on "com.github.CaffeineMC:sodium-fabric:1.16.x~next-SNAPSHOT" that can't be loaded. I didn't get to fix it so here I am writing this issues report hoping you can fix it so I can start coding addons for this beautiful client.

**Comment by seasnail8169** [comment]
Known and cant be fixed until sodium is at least.
