### ISSUE TITLE
The Log4j thingy.

### ISSUE THREAD

**Issue by ed0cinU** [MeteorDevelopment/meteor-addon-template#10]
Idk if its your fault or the fault from the fabric team but the **log4j version used in this project isn't up to date**.
![image](https://user-images.githubusercontent.com/58796076/147415307-d0042bdd-f157-47b1-9697-25307399136e.png)

**Comment by Justgamer101** [comment]
you can change the fabric version in the gradle.properties file. [This](https://fabricmc.net/versions.html) is the link to fabric versions site.
