### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by maxsupermanhd** [MeteorDevelopment/meteor-addon-template#25]
At some point my intellij stopped building projects that have meteor snapshot in them.

```
A problem occurred configuring root project 'meteor-addon-template'.
> Could not find meteor-client-0.5.1-SNAPSHOT.jar (meteordevelopment:meteor-client:0.5.1-SNAPSHOT:20220926.112654-59).
  Searched in the following locations:
      https://maven.meteordev.org/snapshots/meteordevelopment/meteor-client/0.5.1-SNAPSHOT/meteor-client-0.5.1-20220926.112654-59.jar
```

Tried re-cloning repositories and cleaning caches in intellij but error persists.
Anyone knows how to fix it?

**Comment by maxsupermanhd** [comment]
I ended up resetting my settings to default ones but that's not a great solution

**Comment by DesiCow** [comment]
Replace `modImplementation "meteordevelopment:meteor-client:0.5.2-SNAPSHOT"` with 
```gradle
modImplementation("meteordevelopment:meteor-client") {
        version {
            strictly "0.5.2-SNAPSHOT"
        }
    }
```

**Comment by CrytoPal** [comment]
I'm having the same issue:

Could not find meteor-client-0.5.2-SNAPSHOT.jar (meteordevelopment:meteor-client:0.5.2-SNAPSHOT:20230123.224945-43).
  Searched in the following locations:
      https://maven.meteordev.org/snapshots/meteordevelopment/meteor-client/0.5.2-SNAPSHOT/meteor-client-0.5.2-20230123.224945-43.jar

**Comment by maxsupermanhd** [comment]
Seems to be gradle/intellij issue.
Solved by refreshing dependencies of the project: 
![image](https://user-images.githubusercontent.com/20772987/214883627-d2818697-b15e-4085-9566-c41ff9666c00.png)
