### ISSUE TITLE
Unable to build // Could not find fabric-1.19.2-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Luna-DEV-net** [MeteorDevelopment/meteor-addon-template#26]
`A problem occurred configuring root project 'Bypass'.
> Could not find fabric-1.19.2-SNAPSHOT.jar (baritone:fabric:1.19.2-SNAPSHOT:20220809.004850-1).
  Searched in the following locations:
      https://maven.meteordev.org/snapshots/baritone/fabric/1.19.2-SNAPSHOT/fabric-1.19.2-20220809.004850-1.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
`

**Comment by maxsupermanhd** [comment]
Same for me, and I thought it is problem with my setup but seems like it is not

**Comment by maxsupermanhd** [comment]
What worked for me is refreshing dependencies in the gradle tab in context menu of a project btw
