### ISSUE TITLE
Wait what

### ISSUE THREAD

**Issue by BDARmech** [MeteorDevelopment/meteor-addon-template#33]
Wait what

_Originally posted by @I-Got-You-Dead2 in https://github.com/MeteorDevelopment/meteor-client/issues/3647#issuecomment-1539726702_
            You threaten anyone with doxing again and I will deal with it.

**Comment by I-Got-You-Dead2** [comment]
I will dox you

**Comment by I-Got-You-Dead2** [comment]
:trollface:

**Comment by BDARmech** [comment]
> I will dox you

When how or why I seek someone out sets in, Let me know.

**Comment by BDARmech** [comment]
> ```
>           Wait what
> ```
> 
> _Originally posted by @I-Got-You-Dead2 in [MeteorDevelopment/meteor-client#3647 (comment)](https://github.com/MeteorDevelopment/meteor-client/pull/3647#issuecomment-1539726702)_ You threaten anyone with doxing again and I will deal with it.

**Comment by Talhoid** [comment]
what
