### ISSUE TITLE
Crash(Meteor 0.4.7)

### ISSUE THREAD

**Issue by ghost** [MeteorDevelopment/meteor-addon-template#5]
java.lang.NullPointerException: Cannot invoke "meteordevelopment.meteorclient.systems.modules.Modules.isActive(java.lang.Class)" because the return value of "meteordevelopment.meteorclient.systems.modules.Modules.get()" is null

**Comment by arlomcwalter** [comment]
send the whole crash log

**Comment by UnixLudi0** [comment]
[crash-2021-11-18_20.02.19-client.txt](https://github.com/MeteorDevelopment/meteor-addon-template/files/7565463/crash-2021-11-18_20.02.19-client.txt)
